function [SymOps]=gensymops(axs) %Generate symmetry operators for tetragonal symmetry
if axs == 1
    rotter = [1 0 0; 0 0 -1; 0 1 0]*[0 0 1; 0 1 0; -1 0 0];
elseif axs == 2
    rotter = [1 0 0; 0 0 -1; 0 1 0]*[0 0 1; 0 1 0; -1 0 0];
elseif axs == 3
    rotter = eye(3);
end
    for j=1:8
        switch j
            case 1
                S=rotter*[1 0 0;...
                    0 1 0 ;...
                    0 0 1];
            case 2 %C_4z+
                S=rotter*[0 -1 0;...
                    1 0 0;...
                    0 0 1];
            case 3 %C_4z-
                S=rotter*[0 1 0;...
                    -1 0 0;...
                    0 0 1];               
            case 4 %C_2z
                S=rotter*[...
                        -1 0 0;...
                        0 -1 0;...
                        0 0 1];
            case 5 %C_2x
                S=rotter*[...
                        1 0 0;...
                        0 -1 0;...
                        0 0 -1];
            case 6 %C_2y
                S=rotter*[...
                        -1 0 0;...
                        0 1 0;...
                        0 0 -1];
            case 7 %C_2a
                S=rotter*[...
                        0 1 0;...
                        1 0 0;...
                        0 0 -1];
                
            case 8 %C_2b
                S=rotter*[...
                        0 -1 0;...
                        -1 0 0;...
                        0 0 -1];
                
        end    
        SymOps(j,:,:)=S;
    end
        